Repository Filmstund/filmstund, pull requests merged in 2021-12, with the labels that each got.

#601 Add arm64 support for gofumpt & golangci
  tools/gofumpt/rules.mk
  tools/golangci-lint/rules.mk
Labels: feature

#602 fix(tools): go install sqlc
  tools/sqlc/rules.mk
Labels: chore, fix

#603 chore: cleanup unused functions and configs
  go.mod
  go.sum
  internal/auth0/config.go
  internal/middleware/authorization.go
  internal/security/utils.go
  internal/security/utils_test.go
Labels: Backend, chore

#604 feat(session): use persistent sessions
  configs/database/migrations/000004_create_sessions.down.sql
  configs/database/migrations/000004_create_sessions.up.sql
  configs/database/queries/sessions.sql
  internal/database/sqlc/models.go
  internal/database/sqlc/sessions.sql.go
  internal/middleware/recover.go
  internal/session/session.go
  internal/setup/setup.go
Labels: enhancement, Backend, feature

#605 feat(giftcerts): implement add/remove mutations
  configs/database/migrations/000005_create_gift_certificate.down.sql
  configs/database/migrations/000005_create_gift_certificate.up.sql
  configs/database/queries/users.sql
  internal/database/sqlc/models.go
  internal/database/sqlc/users.sql.go
  internal/graph/mappers/user.go
  internal/graph/users.resolvers.go
Labels: enhancement, Backend, feature

#606 refactor(users): extract fetch user func helper
  internal/graph/users.go
  internal/graph/users.resolvers.go
Labels: Backend, chore

#607 chore(db): add movies and showing DB tables
  configs/database/migrations/000006_create_movies.down.sql
  configs/database/migrations/000006_create_movies.up.sql
  configs/database/migrations/000007_create_showing_tables.down.sql
  configs/database/migrations/000007_create_showing_tables.up.sql
  internal/database/sqlc/models.go
Labels: Backend, chore

#617 feat(fsapi): add Ticket downloader
  filmstaden/client.go
  filmstaden/tickets.go
  filmstaden/tickets_test.go
Labels: enhancement, Backend, feature
