Repository Filmstund/filmstund, pull requests merged in 2022-01, with the labels that each got.

#630 feat: add query functions for movies and shows from Filmstaden
  .gitattributes
  filmstaden/client.go
  filmstaden/get_movies.go
  filmstaden/get_movies_test.go
  filmstaden/get_shows.go
  filmstaden/get_shows_test.go
  filmstaden/get_tickets.go
  filmstaden/get_tickets_test.go
  filmstaden/testdata/movies-upcoming-detailed.json
  filmstaden/testdata/movies-upcoming.json
  filmstaden/testdata/movies.json
  filmstaden/testdata/shows-stripped_1_GB.json
Labels: Backend, feature

#631 refactor: rename date -> time
  api/graphql/v2/scalars.graphqls
  api/graphql/v2/users.graphqls
  configs/database/migrations/000002_create_commandment_table.up.sql
  configs/database/migrations/000003_create_users.up.sql
  configs/database/migrations/000004_create_gift_certificate.up.sql
  configs/database/migrations/000005_create_movies.up.sql
  configs/database/migrations/000006_create_showing_tables.up.sql
  configs/database/queries/users.sql
  internal/database/dao/models.go
  internal/database/dao/users.sql.go
  internal/graph/gql/runtime.go
  internal/graph/mappers/user.go
  internal/graph/model/models_gen.go
  internal/graph/users.resolvers.go
Labels: Backend, chore

#642 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: chore

#643 feat(db): support database transactions
  filmstaden/get_movies.go
  internal/database/connections.go
  internal/graph/movie.resolvers.go
Labels: Backend, feature

#645 chore(web): update gql typings
  web/schema.graphql
  web/src/__generated__/types.ts
Labels: Frontend, chore

#646 feat(movies): support city alias when fetching
  api/graphql/v2/movie.graphqls
  internal/graph/gql/runtime.go
  internal/graph/movie.resolvers.go
  web/schema.graphql
  web/src/__generated__/types.ts
Labels: Backend, feature

#647 chore(graphql): generate most missing types
  Makefile
  api/graphql/v1/location.graphqls
  api/graphql/v1/movie.graphqls
  api/graphql/v1/payment.graphqls
  api/graphql/v1/scalars.graphqls
  api/graphql/v1/showing.graphqls
  api/graphql/v1/user.graphqls
  api/graphql/v2/filmstaden.graphqls
  api/graphql/v2/movies.graphqls
  api/graphql/v2/payment.graphqls
  api/graphql/v2/scalars.graphqls
  api/graphql/v2/showing.graphqls
  api/graphql/v2/ticket.graphqls
  api/graphql/v2/users.graphqls
  configs/gqlgen.yml
  internal/database/dao/mapper_movies.go
  internal/database/dao/mapper_users.go
  internal/graph/commandments.resolvers.go
  internal/graph/gql/runtime.go
  internal/graph/mappers/user.go
  internal/graph/model/models_gen.go
  internal/graph/movies.resolvers.go
  internal/graph/payment.resolvers.go
  internal/graph/showing.resolvers.go
  internal/graph/users.go
  internal/graph/users.resolvers.go
  web/schema.graphql
  web/src/__generated__/types.ts
  web/src/use-cases/common/showing/fragment.ts
  web/src/use-cases/my-showings/Home.tsx
Labels: Backend, Frontend, chore

#651 chore(fsid): implement ID format validation
  internal/graph/scalars/filmstadenmembershipid.go
  internal/graph/scalars/filmstadenmembershipid_test.go
Labels: Backend, chore

#657 fix: create giftcards and create showings
  api/graphql/users.graphqls
  internal/graph/gql/runtime.go
  web/codegen.yml
  web/schema.graphql
  web/src/LoginGate.tsx
  web/src/__generated__/introspection.json
  web/src/__generated__/types.ts
  web/src/store/urql.ts
  web/src/use-cases/common/showing/FilmstadenShowingSelector.tsx
  web/src/use-cases/common/ui/NavBar.jsx
  web/src/use-cases/common/ui/date-picker/DatePickerInput.tsx
  web/src/use-cases/common/utils/ProjectorLoader.tsx
  web/src/use-cases/login/components/login-styles.tsx
  web/src/use-cases/login/containers/Login.tsx
  web/src/use-cases/login/containers/assets/google-logo.svg
  web/src/use-cases/login/containers/assets/logo.png
  web/src/use-cases/my-showings/utils/filtersCreators.ts
  web/src/use-cases/new-showing/CreateShowingForm.tsx
  web/src/use-cases/single-showing/utils/__tests__/createPaymentOptions.test.ts
  web/src/use-cases/user/DateInput.tsx
  web/src/use-cases/user/EditableForetagsbiljettList.tsx
  web/src/use-cases/user/Foretagsbiljett.tsx
  web/src/use-cases/user/ForetagsbiljettList.tsx
  web/yarn.lock
Labels: feature, fix

#659 fix: format showing dates
  web/src/use-cases/common/showing/Showing.tsx
  web/src/use-cases/my-showings/Home.tsx
  web/src/use-cases/showings-list/Showings.tsx
  web/src/use-cases/single-showing/containers/SingleShowingContainer.tsx
Labels: feature, fix

#661 feat: set default showing time to 19:00
  web/src/use-cases/new-showing/CreateShowingForm.tsx
Labels: feature

#660 fix: format showing time as hh:mm
  web/src/use-cases/common/ui/SelectBox.tsx
Labels: feature, fix

#673 fix(ci): allow frontend to build
  .github/workflows/deploy-beta-backend.yml
  .github/workflows/deploy-beta-frontend.yml
Labels: fix

#674 fix(ci): reference preprod environment
  .github/workflows/deploy-beta-backend.yml
  .github/workflows/deploy-beta-frontend.yml
Labels: fix

#675 fix(ci): include secrets for replace job
  .github/workflows/deploy-beta-backend.yml
  .github/workflows/deploy-beta-frontend.yml
Labels: fix

#676 fix(ci): add `--force` flag when replacing frontend
  .github/workflows/deploy-beta-frontend.yml
Labels: fix

#677 feat(ci): add deployment url to the frontend
  .github/workflows/deploy-beta-backend.yml
  .github/workflows/deploy-beta-frontend.yml
Labels: feature

#678 refactor(ci): combine workflows
  .github/workflows/backend.yml
  .github/workflows/checks.yml
  .github/workflows/ci.yml
  .github/workflows/deploy-beta-frontend.yml
  .github/workflows/deploy-beta.yml
  .github/workflows/frontend.yml
Labels: ci

#679 chore(ci): add specific node version on deploy
  .github/workflows/deploy-beta.yml
Labels: chore, ci

#688 fix: update cache after mutation
  README.md
  web/src/__generated__/types.ts
  web/src/store/urql.ts
  web/src/use-cases/common/showing/movieFragment.graphql
  web/src/use-cases/new-showing/MovieSelector.tsx
Labels: feature, fix

#689 fix(movies): return all movies when fetching new ones
  internal/graph/movies.resolvers.go
Labels: Backend, fix

#691 fix: transform location to location selector options
  web/src/common/toast/ToastContext.tsx
  web/src/common/toast/Toaster.tsx
  web/src/use-cases/common/ui/LocationSelect.jsx
  web/src/use-cases/common/ui/LocationSelect.tsx
  web/src/use-cases/edit-showing/EditShowingForm.tsx
  web/src/use-cases/new-showing/CreateShowingForm.tsx
Labels: feature, fix

#692 lint: remove unused variable
  web/src/use-cases/new-showing/MovieSelector.tsx
Labels: feature

#694 fix(attendee): add ID field
  api/graphql/payment.graphqls
  internal/graph/gql/runtime.go
  internal/graph/model/models_gen.go
  internal/graph/payment.helpers.go
  internal/graph/payment.helpers_test.go
  internal/graph/payment.resolvers.go
  web/schema.graphql
  web/src/__generated__/introspection.json
  web/src/__generated__/types.ts
Labels: Backend, fix

#696 docs(readme): update CI badges
  README.md
Labels: documentation

#697 feat(tickets): implement ticket range resolver
  configs/database/queries/tickets.sql
  internal/database/dao/tickets.sql.go
  internal/graph/ticket.helpers.go
  internal/graph/ticket.resolvers.go
Labels: Backend, feature

#698 refactor(makefile): homogenize Makefiles
  .github/workflows/ci.yml
  Makefile
  web/Makefile
Labels: fix, ci

#699 fix(payment): return nil when there are no attendees
  internal/graph/payment.resolvers.go
Labels: Backend, fix

#700 fix(filmstaden): link directly to showing if we can
  internal/graph/payment.resolvers.go
Labels: Backend, fix

#701 fix: use new option.value instead of the old value
  web/src/use-cases/common/ui/LocationSelect.tsx
Labels: fix

#702 fix(tickets): more robust ticket assignment
  configs/database/queries/tickets.sql
  internal/database/dao/tickets.sql.go
  internal/graph/ticket.helpers.go
Labels: Backend, fix

#703 fix(web): replace sefilm with Filmstund in title
  web/Dockerfile
  web/nginx.conf
  web/src/App.tsx
Labels: Frontend, fix

#719 chore: remove auth0 dependency
  web/package.json
  web/yarn.lock
Labels: chore, fix

#720 chore(ci): add bundlesize tracking plugin
  .github/workflows/ci.yml
  web/Makefile
  web/package.json
  web/yarn.lock
Labels: chore, feature

#723 chore(web): use new react vite plugin
  web/package.json
  web/vite.config.ts
  web/yarn.lock
Labels: chore, feature

#721 chore: add docker-compose file for postgres & redis
  README.md
  docker-compose.yml
Labels: chore, feature
